name: Unity Multi-Platform Build

on:
  push:
    branches:
      - main
      - unity
  pull_request:
    branches:
      - main
      - unity

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        targetPlatform: [StandaloneWindows64, StandaloneOSX, StandaloneLinux64]
        include:
          - targetPlatform: StandaloneWindows64
            os: windows-latest
          - targetPlatform: StandaloneOSX
            os: macos-latest
          - targetPlatform: StandaloneLinux64
            os: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ github.sha }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-

      - name: Set up Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: '2022.3.5f1' # Adjust the Unity version as needed
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Build Unity Project
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: '2022.3.5f1'
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: ./RacingSimulator
          buildName: RacingSimulator-${{ matrix.targetPlatform }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: ./RacingSimulator/Builds/${{ matrix.targetPlatform }}
          retention-days: 5